force-app/main/default/objects/Bypass_Trigger_Settings__mdt/Bypass_Trigger_Settings__mdt.object-meta.xml
<CustomObject>
    <description>This metadata setting enables system admin to take control of Triggers and allow user to enable/disable trigger, or even certain events or even a certain functionality.</description>
    <label>Bypass Trigger Settings</label>
    <pluralLabel>Bypass Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bypass_Trigger_Settings__mdt/fields/Disabled_Events__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Events__c</fullName>
    <description>Provide Event names in a comma separated values, which we want to Disable</description>
    <inlineHelpText>Provide Event names in a comma separated values, which we want to Disable 
Supported values are - 
BEFORE_INSERT, BEFORE_UPDATE, BEFORE_DELETE,AFTER_INSERT, AFTER_UPDATE, AFTER_DELETE, and AFTER_UNDELETE</inlineHelpText>
    <label>Disabled Events</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Bypass_Trigger_Settings__mdt/fields/Disabled_Methods__c.field-meta.xml
<CustomField>
    <fullName>Disabled_Methods__c</fullName>
    <description>Provide Method names in a comma separated values, which we want to Disable</description>
    <inlineHelpText>Provide Method names in a comma separated values, which we want to Disable</inlineHelpText>
    <label>Disabled Methods</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Bypass_Trigger_Settings__mdt/fields/Is_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Is_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Control Switch to Turn Trigger On or Off</description>
    <inlineHelpText>Deselect to switch off the whole Trigger</inlineHelpText>
    <label>Is Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bypass_Trigger_Settings__mdt/fields/Permission_Name__c.field-meta.xml
<CustomField>
    <fullName>Permission_Name__c</fullName>
    <label>Permission Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bypass_Trigger_Settings__mdt/fields/Trigger_Configurations__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Configurations__c</fullName>
    <label>Trigger Configurations</label>
    <referenceTo>Trigger_Configurations__mdt</referenceTo>
    <relationshipName>Trigger_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Bypass_Trigger_Settings__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
            <value>
                <fullName>Custom Permission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Configurations__mdt/Trigger_Configurations__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Configurations</label>
    <pluralLabel>Trigger Configurations</pluralLabel>
</CustomObject>

force-app/main/default/classes/BypassSettings.cls
public class BypassSettings{
    
    public String  key {get;set;}
    public String  disabledEvents {get;set;}
    public String  disabledMethods {get;set;}        
    public Boolean isTriggerEnabled {get;set;}    
    
    public static BypassSettings getApplicableBypassSettingForTrigger(String Key) {
        Map<String, Bypass_Trigger_Settings__mdt> bypassTriggerSettingsMap = Bypass_Trigger_Settings__mdt.getAll();
        Trigger_Configurations__mdt triggerConfig = Trigger_Configurations__mdt.getInstance(key);
        BypassSettings applicableBypassSetting = null;
        if(triggerConfig==null){
            return applicableBypassSetting;
        }       
        for(Bypass_Trigger_Settings__mdt bypassTriggerSetting : bypassTriggerSettingsMap.values()){
            if(bypassTriggerSetting.Trigger_Configurations__c != triggerConfig.Id){
                continue;
            }
            if(bypassTriggerSetting.Type__c=='Default'&&applicableBypassSetting==null){
                applicableBypassSetting = converToBypassSetting(bypassTriggerSetting,key);
            }else if(bypassTriggerSetting.Type__c=='Custom Permission' && (FeatureManagement.checkPermission(bypassTriggerSetting.Permission_Name__c))){
                if(applicableBypassSetting==null){
                    applicableBypassSetting = converToBypassSetting(bypassTriggerSetting,key);                    
                }else{
                    applicableBypassSetting = combineSettings(applicableBypassSetting,bypassTriggerSetting);
                }                
            }
            
        }   
        return applicableBypassSetting;	
    }
                     
    public static BypassSettings combineSettings(BypassSettings applicableBypassSetting,Bypass_Trigger_Settings__mdt bypassTriggerSetting){
        if(applicableBypassSetting.isTriggerEnabled && bypassTriggerSetting.Is_Enabled__c==false){
            applicableBypassSetting.isTriggerEnabled = bypassTriggerSetting.Is_Enabled__c;
        }
        applicableBypassSetting.disabledMethods = applicableBypassSetting.disabledMethods + bypassTriggerSetting.Disabled_Methods__c;
        applicableBypassSetting.disabledEvents  = applicableBypassSetting.disabledEvents  + bypassTriggerSetting.Disabled_Events__c ;
        return applicableBypassSetting;
    }
    
    public static BypassSettings converToBypassSetting(Bypass_Trigger_Settings__mdt bypassTriggerSetting,String key){
        BypassSettings bypasssetting = new BypassSettings();
        bypasssetting.key = key;
        bypasssetting.isTriggerEnabled = bypassTriggerSetting.Is_Enabled__c;
        bypasssetting.disabledMethods = bypassTriggerSetting.Disabled_Methods__c;
        bypasssetting.disabledEvents = bypassTriggerSetting.Disabled_Events__c;
        return bypasssetting;
    }
}